# Generated by Django 3.2 on 2021-04-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FctMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('input_volume', models.FloatField(null=True)),
                ('output_volume', models.FloatField(null=True)),
                ('difference_volume', models.FloatField(null=True)),
                ('hauptzeit', models.FloatField()),
                ('standmenge', models.FloatField()),
                ('losgroesse', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('classifier', models.CharField(max_length=255)),
                ('is_positive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('restfertigungsgemeinkosten', models.FloatField()),
                ('anschaffungswert', models.FloatField()),
                ('verkaufserlös', models.FloatField()),
                ('abschreibungsdauer', models.FloatField()),
                ('platzbedarf', models.FloatField()),
                ('mittlere_leistung', models.FloatField()),
                ('instandhaltungsfaktor', models.FloatField()),
                ('quadratmeterpreis', models.FloatField()),
                ('strompreis', models.FloatField()),
                ('zinsatz', models.FloatField()),
                ('stundenlohn', models.FloatField()),
                ('fertigungsmittelanzahl', models.FloatField()),
                ('bediehnverhaeltnis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('verteilzeit', models.FloatField()),
                ('ruestzeit', models.FloatField()),
                ('erholungszeit', models.FloatField()),
                ('werkzeugwechselzeit', models.FloatField()),
                ('werkstueckwechselzeit', models.FloatField()),
                ('betriebsstoffkosten', models.FloatField()),
                ('werkzeugpreis', models.FloatField()),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_type', models.CharField(choices=[('prismatisch', 'Prismatisch'), ('rotationssymmetrisch', 'Rotationssymmetrisch'), ('initial_feature', 'Initial Feature'), ('absatz', 'Absatz'), ('t-nut', 'T-Nut'), ('nut', 'Nut'), ('tasche', 'Tasche'), ('passfeder', 'Passfeder'), ('bohrung', 'Bohrung'), ('zylindersenkung', 'Zylindersenkung'), ('kegelsenkung', 'Kegelsenkung'), ('wellenabsatz-zylindrisch', 'Wellenabsatz-Zylindrisch'), ('wellenabsatz-konisch', 'Wellenabsatz-Konisch'), ('innengewinde', 'Innengewinde')], max_length=255)),
                ('hoehe', models.FloatField(blank=True, null=True)),
                ('breite', models.FloatField(blank=True, null=True)),
                ('laenge', models.FloatField(blank=True, null=True)),
                ('tiefe', models.FloatField(blank=True, null=True)),
                ('durchmesser', models.FloatField(blank=True, null=True)),
                ('breite_fuss', models.FloatField(blank=True, null=True)),
                ('tiefe_fuss', models.FloatField(blank=True, null=True)),
                ('winkel', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.feature')),
            ],
        ),
        migrations.CreateModel(
            name='ToolAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
                ('d', models.FloatField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tool')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('laufzeit_jahr', models.FloatField()),
                ('betrachtungszeitraum', models.FloatField()),
                ('produktpreis', models.FloatField()),
                ('materialpreis', models.FloatField()),
                ('materialdichte', models.FloatField()),
                ('lohnnebenkostenanteil', models.FloatField()),
                ('dichte', models.FloatField()),
                ('kilopreis', models.FloatField()),
                ('technologies', models.ManyToManyField(through='main.FctMembership', to='main.Tool')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('compare_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_reference', to='main.referencesystem')),
                ('reference', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.referencesystem')),
            ],
        ),
        migrations.CreateModel(
            name='Halbzeug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoehe', models.FloatField(null=True)),
                ('laenge', models.FloatField(null=True)),
                ('breite', models.FloatField(null=True)),
                ('durchmesser', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureAttributeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.feature')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.feature')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
        migrations.AddField(
            model_name='fctmembership',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.referencesystem'),
        ),
        migrations.AddField(
            model_name='fctmembership',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tool'),
        ),
        migrations.CreateModel(
            name='FctAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.FloatField()),
                ('output', models.FloatField()),
                ('difference', models.FloatField()),
                ('input_possible', models.CharField(choices=[('possible', 'Machbar'), ('experimental', 'Experimental'), ('possible', 'Nicht machbar')], max_length=255)),
                ('output_possible', models.CharField(choices=[('possible', 'Machbar'), ('experimental', 'Experimental'), ('possible', 'Nicht machbar')], max_length=255)),
                ('feature_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.featureattribute')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fctmembership')),
                ('tool_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.toolattribute')),
            ],
        ),
    ]
