# Generated by Django 3.2 on 2021-04-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_mpf_max_result_npf_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='add_to_fct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
