# Generated by Django 3.2 on 2021-04-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_feature_add_to_fct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencesystem',
            name='materialdichte',
        ),
        migrations.RemoveField(
            model_name='referencesystem',
            name='materialpreis',
        ),
    ]
