# Generated by Django 3.2 on 2021-04-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210418_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gpf', models.FloatField()),
                ('Kf_fpf', models.FloatField()),
                ('Kh', models.FloatField()),
                ('Kh_npf', models.FloatField()),
                ('Kma', models.FloatField()),
                ('Krm', models.FloatField()),
                ('npf_max', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
        ),
    ]
