# Generated by Django 3.2 on 2021-04-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_costreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costreference',
            name='item',
        ),
        migrations.AddField(
            model_name='costreference',
            name='reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.referencesystem'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EcrCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G', models.FloatField()),
                ('Kh', models.FloatField()),
                ('npf', models.FloatField()),
                ('Kma', models.FloatField()),
                ('Krm', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
        ),
    ]
