# Generated by Django 3.2 on 2021-04-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210420_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolattribute',
            name='einheit',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
