# Generated by Django 3.2 on 2021-04-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_toolattribute_einheit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolattribute',
            name='einheit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
