# Generated by Django 3.2 on 2021-05-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_toolattribute_einheit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fctattribute',
            name='input_possible',
            field=models.CharField(choices=[('technologisch machbar', 'Machbar'), ('technologische Machbarkeit mit Unsicherheiten', 'technologische Machbarkeit mit Unsicherheiten'), ('technologisch machbar', 'technologisch NICHT umsetzbar')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fctattribute',
            name='output_possible',
            field=models.CharField(choices=[('technologisch machbar', 'Machbar'), ('technologische Machbarkeit mit Unsicherheiten', 'technologische Machbarkeit mit Unsicherheiten'), ('technologisch machbar', 'technologisch NICHT umsetzbar')], max_length=255),
        ),
        migrations.CreateModel(
            name='EcrFuzzy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('m_name', models.CharField(max_length=255)),
                ('tool_name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('fuzzy', models.CharField(max_length=255)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.result')),
            ],
        ),
    ]
